# Generated by Django 3.2.7 on 2021-10-08 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_text', models.CharField(max_length=200, verbose_name='reason for leave')),
                ('leave_approved_status', models.CharField(choices=[('Y', 'Approve'), ('P', 'Pending')], default='P', max_length=1)),
                ('leave_taken_date', models.DateField()),
                ('leave_month', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave',
            },
        ),
    ]
